workflows:
  ios-simulator-build:
    name: Build iOS Simulator App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build for iOS simulator
        script: |
          flutter build ios
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
