// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC57gPRI48XT7R1qtggB60AqUbLYmDStLg",
    authDomain: "daily-planner-4a99c.firebaseapp.com",
    projectId: "daily-planner-4a99c",
    storageBucket: "daily-planner-4a99c.firebasestorage.app",
    messagingSenderId: "425200153710",
    appId: "1:425200153710:web:506c89518560272908627f",
    measurementId: "G-0S1VHE1TVC"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57gPRI48XT7R1qtggB60AqUbLYmDStLg',
    appId: '1:425200153710:web:506c89518560272908627f',
    messagingSenderId: '425200153710',
    projectId: 'daily-planner-4a99c',
    storageBucket: 'daily-planner-4a99c.firebasestorage.app',
  );
}
